version: '2'
services:
  rancher-cowsay-goproverb-ui:
    scale: 1
    metadata:
      alert_rules: |
        ALERT UIReceivedMoreThan10RequestsAMinute
          IF increase(caddy_http_request_count_total{host="www.ranchermeetup.baillie.cloud"}[1m]) > 10 
          FOR 1m
          LABELS { severity = "page" }
          ANNOTATIONS {
            summary = "Caddy webserver instance {{ $$labels.instance }} served more than 10 requests in a minute, OMG!",
            description = "The site {{ $$labels.host }} received {{ humanize $$value }} requests in the last minute"
            }

        ALERT UIRequestLatencyBreachingSLA
          IF sum(meetup_client_side_proverb_latency_milliseconds_sum / meetup_client_side_proverb_latency_milliseconds_count) without (instance) > 1500
          FOR 1m
          LABELS { severity = "page" }
          ANNOTATIONS {
            summary = "UI calls to Rancher Cowsay Goproverb API are breaching SLA of 1.5s from the browser",
            description = "The browser latency is currently {{ humanize $$value }}"
            }

        ## Application Performance Index (https://en.wikipedia.org/wiki/Apdex)
        ALERT UIApdexScoreBreach 
          IF (sum(rate(meetup_client_side_proverb_latency_milliseconds_bucket{le="500"}[5m])) +
              sum(rate(meetup_client_side_proverb_latency_milliseconds_bucket{le="1000"}[5m]))) /
              2 / sum(rate(meetup_client_side_proverb_latency_milliseconds_count[5m])) < 0.5
          LABELS { severity = "page" }
          ANNOTATIONS {
            summary = "Rancher Cowsay Goproverb UI is breaching it's Apdex score to users!!",
            description = "Apdex current value: {{ $$value }}"
            }
